# Import Numpy as np

In [1]:
import numpy as np

Create Array of 10 zeros

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create array of 10 fives

In [4]:
print(np.ones(10,dtype = int)*5)

[5 5 5 5 5 5 5 5 5 5]


Create an array of the integers from 10 to 50

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Create an array of all the even integers from 10 to 50

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create a 3x4 matrix with numbers ranging from 0 to 12

In [7]:
np.arange(3*4).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Create a 3x3 identity matrix

In [8]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [9]:
np.diag([1,1,1])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Use Numpy to generate a random number between 0 and 1

In [10]:
a = np.random.rand() #uniform distribution

In [11]:
a

0.9142270623535627

Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution

In [12]:
np.random.randn(25) #normal Distributuion

array([-1.50284012,  0.55268517,  0.05675967, -0.30899794, -0.32206156,
       -1.03204744,  2.07102599, -0.19369461,  0.79965824, -0.56934823,
        0.53898236,  1.58502968, -1.02737796,  0.0025953 ,  0.98985087,
        0.02629416, -0.30338261,  0.16677287,  1.32969765, -0.12198495,
        0.49210117,  0.97486176, -0.75482844,  0.45018893,  0.07657543])

Create an (10x10)array having numbers from 0.01 to 1 increasing by 0.01

In [13]:
np.arange(0.00,1,0.01).reshape((10,10))

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

Numpy Indexing and Slicing

In [14]:
ar = (np.arange(25)+1).reshape(5,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

extract array

[ [12,13,14],

[17,18,19],

[22,23,24] ]

In [15]:
ar[2:,1:4]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

extract array

[ [14, 13, 12],

[19, 18, 17],

[24, 23, 22] ]

In [16]:
ar[2:,3:0:-1]

array([[14, 13, 12],
       [19, 18, 17],
       [24, 23, 22]])

extract array

[ [24, 23, 22],

[19, 18, 17],

[14, 13, 12],
]


In [17]:
ar[4:1:-1,3:0:-1]

array([[24, 23, 22],
       [19, 18, 17],
       [14, 13, 12]])

#Split Concatinate

In [18]:
ar = np.arange(2,10)
ar

array([2, 3, 4, 5, 6, 7, 8, 9])

Split array to generate 3 arrays with content

[2,3,4]

[5, 6]

[]

[7,8,9]

In [21]:
np.split(ar, [3,5,5]) #Structure of split is that array with splitting address. 

[array([2, 3, 4]), array([5, 6]), array([], dtype=int64), array([7, 8, 9])]

# Concatinate array to create new array with content

In [24]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[3,4,5],[7,8,9]])

In [25]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5],
       [7, 8, 9]])

In [26]:
np.hstack((a,b))

array([[1, 2, 3, 3, 4, 5],
       [4, 5, 6, 7, 8, 9]])

# Broadcasting and Indexing

In [27]:
ar = np.round(np.random.rand(10)*10)
ar

array([3., 5., 2., 3., 8., 2., 4., 8., 1., 9.])

**Create new array containing all numbers which are smaller than 10 in ar**

In [28]:
l=[]
for i in ar:
  if i <10:
    l.append(i)

np.array(l)    

array([3., 5., 2., 3., 8., 2., 4., 8., 1., 9.])

Count how many numbers are minimum in ar

In [29]:
min(ar)

1.0

In [30]:
c=0
for i in ar:
  if i == min(ar):
    c=c+1
print(c)    


1


Create an array of length 20 with first 15 numbers equal to 2 and last 5 numbers = -5

In [35]:
a = np.array(np.ones(15,dtype = int)*2)

In [36]:
a

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [39]:
b=np.array(np.ones(5,dtype=int)*5)
b

array([5, 5, 5, 5, 5])

In [40]:
c = np.concatenate((a,b))

In [41]:
c

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5, 5, 5])

#Sum min max of all elements of matrix

In [48]:
mat = (np.random.rand(12)*100).reshape(3,4)

In [49]:
mat

array([[81.65893766, 53.12862152, 49.75958518, 38.91290234],
       [20.5851103 , 43.79857888, 63.87998956, 53.60215819],
       [84.14174741, 71.77254678, 95.80874581, 14.63436088]])

In [50]:
print(mat.max())
print(mat.min())
print(mat.sum())

95.80874580827292
14.634360883977637
671.683284507914


In [51]:
mat.std()

23.813591554912904

#Sum of all columns of mat

In [53]:
mat.sum(axis=0)

array([186.38579537, 168.69974718, 209.44832055, 107.14942141])